# Generated by Django 2.2.7 on 2019-11-11 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atleta', '0005_auto_20191111_0313'),
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='atleta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atleta_equipe', to='atleta.Atleta'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='treinador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treinador_equipe', to='treinador.Treinador'),
        ),
    ]
