# Generated by Django 2.2.7 on 2019-11-11 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0002_auto_20191111_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='atleta',
        ),
    ]
