# Generated by Django 2.2.7 on 2019-11-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleta', '0006_remove_atleta_equipe'),
        ('equipe', '0003_remove_equipe_atleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='atletas',
            field=models.ManyToManyField(related_name='atletas_equipe', to='atleta.Atleta'),
        ),
    ]
