# Generated by Django 2.2.7 on 2019-11-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0004_equipe_atletas'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='principal',
            field=models.BooleanField(default=False),
        ),
    ]
