# Generated by Django 2.2.7 on 2019-11-11 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipe', '0005_equipe_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('esporte', models.CharField(choices=[('Futebol', 'Futebol'), ('Volei', 'Volei'), ('Natacao', 'Natação'), ('Luta', 'Luta')], default='Futebol', max_length=20)),
                ('equipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treinador_equipe', to='equipe.Equipe')),
            ],
        ),
    ]
