# Generated by Django 2.2.7 on 2019-11-12 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('treinador', '0003_treinador_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinador',
            name='credencial',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='treinador',
            name='detalhes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='treinador',
            name='nascimento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
