# Generated by Django 2.2.7 on 2019-11-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('nascimento', models.DateField()),
                ('peso', models.IntegerField()),
                ('altura', models.IntegerField()),
                ('detalhes', models.TextField()),
                ('documento', models.CharField(max_length=80)),
                ('condicao_fisica', models.CharField(choices=[('EM CONDICOES', 'EM CONDICOES'), ('SEM CONDICOES', 'SEM CONDICOES'), ('NAO AVALIADO', 'NAO AVALIADO')], default='NAO AVALIADO', max_length=10)),
                ('treinador', models.IntegerField()),
                ('equipe', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=10)),
            ],
        ),
    ]
