# Generated by Django 2.2.7 on 2019-11-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='altura',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='peso',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
    ]
