# Generated by Django 2.2.7 on 2019-11-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleta', '0002_auto_20191111_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='condicao_fisica',
            field=models.CharField(choices=[('EM CONDICOES', 'EM CONDICOES'), ('SEM CONDICOES', 'SEM CONDICOES'), ('NAO AVALIADO', 'NAO AVALIADO')], default='NAO AVALIADO', max_length=20),
        ),
    ]
