# Generated by Django 2.2.7 on 2019-11-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleta', '0004_auto_20191111_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
