# Generated by Django 2.2.7 on 2019-11-11 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atleta', '0005_auto_20191111_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atleta',
            name='equipe',
        ),
    ]
