# Generated by Django 2.2.7 on 2019-11-11 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atleta', '0006_remove_atleta_equipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atleta',
            name='treinador',
        ),
    ]
