# Generated by Django 2.2.7 on 2019-11-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleta', '0007_remove_atleta_treinador'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='senha',
            field=models.CharField(default='', max_length=255),
        ),
    ]
