# Generated by Django 2.2.7 on 2019-11-11 23:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atleta', '0008_atleta_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='detalhes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='documento',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='nascimento',
            field=models.DateField(default=datetime.datetime(2019, 11, 11, 23, 20, 21, 944118, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='nome',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
