# Generated by Django 2.2.7 on 2019-11-12 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('atleta', '0009_auto_20191111_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='nascimento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
