# Generated by Django 2.2.7 on 2019-11-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treinador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'treinador',
            },
        ),
    ]
